-- 資料庫 1
CREATE DATABASE IF NOT EXISTS wordpress1;
CREATE USER IF NOT EXISTS 'user1'@'%' IDENTIFIED BY 'password1';
GRANT ALL PRIVILEGES ON wordpress1.* TO 'user1'@'%';

-- 資料庫 2
CREATE DATABASE IF NOT EXISTS wordpress2;
CREATE USER IF NOT EXISTS 'user2'@'%' IDENTIFIED BY 'password2';
GRANT ALL PRIVILEGES ON wordpress2.* TO 'user2'@'%';

-- 資料庫 3
CREATE DATABASE IF NOT EXISTS wordpress3;
CREATE USER IF NOT EXISTS 'user3'@'%' IDENTIFIED BY 'password3';
GRANT ALL PRIVILEGES ON wordpress3.* TO 'user3'@'%';

FLUSH PRIVILEGES;